export const WSELF__INIT = 'WSELF__INIT';

export const WSELF__DESTROY = 'WSELF__DESTROY';

export const WORKER__INIT = 'WORKER__INIT';

export const WORKER__POST_MESSAGE = 'WORKER__POST_MESSAGE';

export const WORKER__DESTROY = 'WORKER__DESTROY';

export const WORKER__SUBSCRIBE = 'WORKER__SUBSCRIBE';

export const WORKER__UNSUBSCRIBE = 'WORKER__UNSUBSCRIBE';
